name = "kakurega"
compatibility_date = "2024-10-31"
pages_build_output_dir = "build"

[env.development]
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_flags = ["nodejs_compat"]

