name = "kakurega"
main = ".svelte-kit/cloudflare/index.js"
compatibility_date = "2024-07-22"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[assets]
directory = ".svelte-kit/cloudflare/assets"
binding = "ASSETS"

